sudo: required

services:
    - docker

before_install:
    - docker build -t tiennguyenftu/docker-react -f Dockerfile.dev .

script:
    - docker run tiennguyenftu/docker-react npm run test -- --coverage --watchAll=false
